---
- hosts: localhost,
  become: true

  tasks:
    - name: Import global variables
      include_vars:
        file: "env.yml"
        name: global
    - name: Install zsh on Arch Linux
      pacman:
        name:
          - zsh
          - curl
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Install zsh on Debian
      apt:
        name:
          - zsh
          - curl
      when: ansible_facts['os_family'] == "Debian"
    - name: Install 'oh-my-zsh'
      shell:
        cmd: /usr/bin/curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        creates: "{{ global.home }}/oh-my-zsh"
    - name: Copy zsh config
      copy:
        src: "{{ global.config_dir }}/.zshrc"
        dest: "{{ global.home }}/.zshrc"
        owner: wittano
