---
- hosts: localhost,
  become: true
  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Install zsh on Arch Linux
      pacman:
        name:
        - zsh
        - curl
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Install zsh on Debian
      apt:
        name: 
        - zsh
        - curl
      when: ansible_facts['os_family'] == "Debian"
    - name: Install 'oh-my-zsh'
      shell:
        cmd: /usr/bin/curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        creates: "{{ home }}/oh-my-zsh"
    - name: Copy zsh config
      copy:
        src: ../.zshrc
        dest: "{{ home }}/.zshrc"
        owner: wittano


