# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.hostname = "wittano.debian.local"

  # config.vm.synced_folder "./data", "/share"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.keymap = "pl"
    libvirt.memory = 2048
    libvirt.storage :file, :size => '10G'
  end
  
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
