# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-'SCRIPT'
  echo "Update system"  
  sudo apt update && sudo apt upgrade -y
  
  echo "Install basic utils"
  sudo apt install -y git ansible vim
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: $script

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.keymap = "pl"
    libvirt.memory = 2048
    libvirt.storage :file, :size => '10G'
  end
  
end
