source $HOME/.config/nvim/plugins/ale.vim
source $HOME/.config/nvim/plugins/coc.vim
source $HOME/.config/nvim/plugins/cpp-syntax.vim
source $HOME/.config/nvim/plugins/golang.vim
source $HOME/.config/nvim/plugins/lightline.vim
source $HOME/.config/nvim/plugins/trailing-whitespace.vim
source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/base.vim
source $HOME/.config/nvim/keymap.vim