#!/bin/bash
nitrogen --restore &
tint2 &
notify-osd &
redshift &
emacs --daemon &
vivaldi &
discord &
spotify &

# for m in $(xrandr --query | awk '{if($2 == "connected"){print $1}}'); do
# 	MONITOR=$m polybar wittano &
# done
